#environment: development
server:
  port: 8044
  servlet:
    context-path: /sshop

spring:
  application:
    name: SSHOP_backend
  datasource:
    url: jdbc:postgresql://localhost:5433/sshop
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update #Hibernate ddl auto options: update, create, drop, create-drop, validate, none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        # jdbc.lob.non_contextual_creation: true #doestn't use sessions to persist effectively
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.security: DEBUG

sshop:
  jwt:
    access-secret-key: f90f6c917536c37e7fe5d56ccaf75534f69dd709089356dbdaefab4fc11c47be1281df3e46d7b24804e3309686775b91a23e29b81ea33d59d6e11af8e5da20b0 #hex 64 bytes
    access-valid-duration: 1D
    refresh-secret-key: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij #base64 64 bytes
    refresh-valid-duration: 7D
  media:
    uri: file:///D:/.Project/kltn/SSHOP_media

